development: 
  cloud_name: "dx9vr7on4"
  api_key: "548375171588668"
  api_secret: "4jAfaZNyF8JA-TUOu1rhMgjTRbk"
  secure: true

production:
  cloud_name: "dx9vr7on4"
  api_key: "548375171588668"
  api_secret: "4jAfaZNyF8JA-TUOu1rhMgjTRbk"
  secure: true

test:
  cloud_name: "dx9vr7on4"
  api_key: "548375171588668"
  api_secret: "4jAfaZNyF8JA-TUOu1rhMgjTRbk"
  secure: true
