# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: music_development

test:
  <<: *default
  database: music_test

production:
  <<: *default
  database: music_production
  username: music
  password: <%= ENV['PEMBR_DATABASE_PASSWORD'] %>
